/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as CaptureOverlayRouteImport } from './routes/capture-overlay'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConversationIndexRouteImport } from './routes/conversation/index'
import { Route as ConversationIdRouteImport } from './routes/conversation/$id'
import { Route as ApiConversationChatRouteImport } from './routes/api.conversation-chat'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureOverlayRoute = CaptureOverlayRouteImport.update({
  id: '/capture-overlay',
  path: '/capture-overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIndexRoute = ConversationIndexRouteImport.update({
  id: '/conversation/',
  path: '/conversation/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIdRoute = ConversationIdRouteImport.update({
  id: '/conversation/$id',
  path: '/conversation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationChatRoute = ApiConversationChatRouteImport.update({
  id: '/api/conversation-chat',
  path: '/api/conversation-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/capture-overlay': typeof CaptureOverlayRoute
  '/menu': typeof MenuRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversation-chat': typeof ApiConversationChatRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/conversation': typeof ConversationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/capture-overlay': typeof CaptureOverlayRoute
  '/menu': typeof MenuRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversation-chat': typeof ApiConversationChatRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/conversation': typeof ConversationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/capture-overlay': typeof CaptureOverlayRoute
  '/menu': typeof MenuRoute
  '/api/chat': typeof ApiChatRoute
  '/api/conversation-chat': typeof ApiConversationChatRoute
  '/conversation/$id': typeof ConversationIdRoute
  '/conversation/': typeof ConversationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Login'
    | '/capture-overlay'
    | '/menu'
    | '/api/chat'
    | '/api/conversation-chat'
    | '/conversation/$id'
    | '/conversation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Login'
    | '/capture-overlay'
    | '/menu'
    | '/api/chat'
    | '/api/conversation-chat'
    | '/conversation/$id'
    | '/conversation'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/capture-overlay'
    | '/menu'
    | '/api/chat'
    | '/api/conversation-chat'
    | '/conversation/$id'
    | '/conversation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CaptureOverlayRoute: typeof CaptureOverlayRoute
  MenuRoute: typeof MenuRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiConversationChatRoute: typeof ApiConversationChatRoute
  ConversationIdRoute: typeof ConversationIdRoute
  ConversationIndexRoute: typeof ConversationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture-overlay': {
      id: '/capture-overlay'
      path: '/capture-overlay'
      fullPath: '/capture-overlay'
      preLoaderRoute: typeof CaptureOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/': {
      id: '/conversation/'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/$id': {
      id: '/conversation/$id'
      path: '/conversation/$id'
      fullPath: '/conversation/$id'
      preLoaderRoute: typeof ConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversation-chat': {
      id: '/api/conversation-chat'
      path: '/api/conversation-chat'
      fullPath: '/api/conversation-chat'
      preLoaderRoute: typeof ApiConversationChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CaptureOverlayRoute: CaptureOverlayRoute,
  MenuRoute: MenuRoute,
  ApiChatRoute: ApiChatRoute,
  ApiConversationChatRoute: ApiConversationChatRoute,
  ConversationIdRoute: ConversationIdRoute,
  ConversationIndexRoute: ConversationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
